version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cart-service-go:
    build:
      context: ../services/cart-service-go
      dockerfile: Dockerfile
    container_name: cart-service-go
    environment:
      - PORT=8081
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - CART_DB_DSN=postgres://cart_user:cart_pass@cart-db:5432/cart_db?sslmode=disable
    depends_on:
      - rabbitmq
      - cart-db
    ports:
      - "8081:8081"

  cart-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=cart_db
      - POSTGRES_USER=cart_user
      - POSTGRES_PASSWORD=cart_pass
    ports:
      - "5433:5432"
    volumes:
      - ../services/cart-service-go/internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  order-service-go:
    build:
      context: ../services/order-service-go
      dockerfile: Dockerfile
    container_name: order-service-go
    environment:
      - PORT=8082
      - ORDER_DB_DSN=postgres://order_user:order_pass@order-db:5432/order_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - order-db
      - rabbitmq
    ports:
      - "8082:8082"
  order-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_pass
    ports:
      - "5434:5432"
    volumes:
      - ../services/order-service-go/internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  inventory-service-go:
    build:
      context: ../services/inventory-service-go
      dockerfile: Dockerfile
    container_name: inventory-service-go
    environment:
      - HTTP_ADDR=:8083
      - DATABASE_DSN=postgres://inventory_user:inventory_pass@inventory-db:5432/inventory_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RUN_MIGRATIONS=true
      - MIGRATIONS_PATH=./internal/db/migrations
    depends_on:
      - rabbitmq
      - inventory-db
    ports:
      - "8083:8083"

  inventory-db:
    image: postgres:16
    container_name: inventory-db
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_pass
    ports:
      - "5435:5432"
    volumes:
      - ../services/inventory-service-go/internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  payment-db:
    image: postgres:16
    container_name: payment-db
    environment:
      - POSTGRES_DB=payment_db
      - POSTGRES_USER=payment_user
      - POSTGRES_PASSWORD=payment_pass
    ports:
      - "5436:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  payment-service-dotnet:
    build:
      context: ../services/payment-service-dotnet
      dockerfile: Dockerfile
    container_name: payment-service-dotnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
      - payment-db
    ports:
      - "8085:8080"

  catalog-service-java:
    build:
      context: ../services/catalog-service-java
      dockerfile: Dockerfile
    container_name: catalog-service-java
    environment:
      - PORT=8086
      - SPRING_DATASOURCE_URL=jdbc:postgresql://catalog-db:5432/catalog_db
      - SPRING_DATASOURCE_USERNAME=catalog_user
      - SPRING_DATASOURCE_PASSWORD=catalog_pass
    depends_on:
      - catalog-db
    ports:
      - "8086:8086"

  catalog-db:
    image: postgres:16
    container_name: catalog-db
    environment:
      - POSTGRES_DB=catalog_db
      - POSTGRES_USER=catalog_user
      - POSTGRES_PASSWORD=catalog_pass
    ports:
      - "5437:5432"
    volumes:
      - catalog_db_data:/var/lib/postgresql/data

  shipping-service-java:
    build:
      context: ../services/shipping-service-java
      dockerfile: Dockerfile
    container_name: shipping-service-java
    environment:
      - PORT=8086

      # Spring RabbitMQ (correct format)
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq:5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

      - SPRING_DATASOURCE_URL=jdbc:postgresql://shipping-db:5432/shipping_db
      - SPRING_DATASOURCE_USERNAME=shipping_user
      - SPRING_DATASOURCE_PASSWORD=shipping_pass
    depends_on:
      - rabbitmq
      - shipping-db
    ports:
      - "8087:8086"   

  shipping-db:
    image: postgres:16
    container_name: shipping-db
    environment:
      - POSTGRES_DB=shipping_db
      - POSTGRES_USER=shipping_user
      - POSTGRES_PASSWORD=shipping_pass
    ports:
      - "5438:5432"   
    volumes:
      - shipping_db_data:/var/lib/postgresql/data



volumes:
  payment_db_data:
  catalog_db_data:
  shipping_db_data:
