version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cart-service-go:
    build:
      context: ../services/cart-service-go
      dockerfile: Dockerfile
    container_name: cart-service-go
    environment:
      - PORT=8081
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - CART_DB_DSN=postgres://cart_user:cart_pass@cart-db:5432/cart_db?sslmode=disable
    depends_on:
      - rabbitmq
      - cart-db
    ports:
      - "8081:8081"

  cart-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=cart_db
      - POSTGRES_USER=cart_user
      - POSTGRES_PASSWORD=cart_pass
    ports:
      - "5433:5432"
    volumes:
      - ../services/cart-service-go/internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  order-service-go:
    build:
      context: ./services/order-service-go
    container_name: order-service-go
    environment:
      - PORT=8082
      - ORDER_DB_DSN=postgres://order_user:order_pass@order-db:5432/order_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - order-db
      - rabbitmq
    ports:
      - "8082:8082"
  order-db:
    image: postgres:16
    environment:
      - POSTGRES_DB=order_db
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=order_pass
    ports:
      - "5434:5432"
    volumes:
      - ./services/order-service-go/internal/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql